name: Deploy

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.78.2"

      - name: Build
        run: hugo --minify

      - name: Prepare SSH Secret
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo '$SSH_SECRET' | envsubst > ~/.ssh/id_ed25519
          echo '$SSH_CONFIG' | envsubst > ~/.ssh/config
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        env:
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}

      - name: Deploy
        run: |
          rsync -e "ssh -o 'StrictHostKeyChecking no'" -avz --delete public/ u.tsukuba.ac.jp:$SSH_PATH
        env:
          SSH_PATH: ${{ secrets.SSH_PATH }}
